apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - argocd-server-config.yaml
  - argocd-ingress.yaml

namespace: argocd

commonLabels:
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/managed-by: kustomize
