apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rippal-production

namespace: rippal

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

commonLabels:
  environment: production

images:
  - name: docker4zerocool/rippal
    newTag: latest