apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rippal-pvc
  namespace: rippal
  labels:
    app: rippal
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
